### ISSUE TITLE
Empty space after ":" breaks the release tag completion

### ISSUE THREAD

**Issue by tomahl** [kilbdev/nova-npm#3]
Hi there,

It seems like the auto completion for the release tag doesn't work if there is an empty space after the ":".

```javascript
{
    "package-name":tag // Works
}

{
    "package-name": tag // Doesn't work
}
```
Thanks for the great extension. 👍

**Comment by kilbd** [comment]
Thank you for submitting this issue, @tomahl!

This definitely worked before. Something must have changed in Nova 2. I also saw that Nova 3 is due to drop in a week or so, and will specifically change when completions are triggered, so a fix might come after that release.

**Comment by kilbd** [comment]
To update where this stands, I was able to verify that the extension is still being triggered and providing completion options. For some reason, the space before the identifier is causing the provided completions to be suppressed. I haven't gotten any clarity from Panic on why the completions don't show, nor guidance on how to ensure they work as expected.

**Comment by kilbd** [comment]
I finally had the time and energy to delve into what was causing this issue. I hope that the new extension version (1.1.0) released today fixes it for everyone. I sincerely appreciate anyone who has continued to use the extension while this issue was unfixed.

Something about how I was trying to helpfully reformat the JSON key/value pair (name/version) was causing it to be suppressed by Nova. Some combination of an expanded replacement range for the completion and starting the inserted text with non-alphanumeric characters was running up against some sort of Nova restriction on completions. I'm still not entirely clear on what rules I was violating to have my completions suppressed.

The good news is that I figured out what I was trying to do would be better accomplished with snippets. One of the biggest benefits is that I can automatically suggest the latest version of a package without users needing to input any additional text. Users can accept this latest version by hitting Enter, or can start typing a different version tag/number.

I'm going to close this issue. If there is an issue with version 1.1.0, please open another issue. Thank you!
